@extends('layouts.app')
@section('title', 'Pricing | ' . config('app.name'))
@push('styles')
<style>.pricing{max-width:1180px;margin:0 auto;padding:70px 24px}.pricing-head{text-align:center;margin-bottom:38px}.pricing-head h1{font-size:38px;color:#0f172a;margin:0}.pricing-head p{color:#64748b}.mode-note{display:inline-block;background:{{ $razorpay->mode() === 'live' ? '#fff7ed' : '#eff6ff' }};color:#334155;border-radius:99px;padding:7px 11px;font-size:12px;font-weight:800}.plans{display:grid;grid-template-columns:repeat(auto-fit,minmax(245px,1fr));gap:18px}.plan{border:1px solid #e2e8f0;border-radius:18px;padding:25px;background:#fff;box-shadow:0 4px 16px rgba(15,23,42,.04)}.plan.popular{border:2px solid #2563eb}.plan h2{font-size:21px;color:#0f172a}.price{font-size:30px;font-weight:800;color:#0f172a;margin:18px 0}.price span{font-size:13px;color:#64748b;font-weight:600}.plan p,.plan li{color:#64748b;font-size:14px}.plan ul{padding-left:18px;line-height:2}.buy{width:100%;border:0;border-radius:10px;background:#2563eb;color:#fff;padding:12px;font-weight:800;cursor:pointer}.buy:disabled{opacity:.55}.notice{margin:0 auto 20px;max-width:600px;padding:12px 15px;border-radius:10px;background:#fef2f2;color:#b91c1c;font-weight:600;font-size:13px}</style>
@endpush
@section('content')
<main class="pricing"><div class="pricing-head"><span class="mode-note">Razorpay {{ strtoupper($razorpay->mode()) }} mode</span><h1>Plans that grow with your center</h1><p>Choose monthly or yearly billing. Payments are securely processed by Razorpay.</p></div>
@if(session('error'))<div class="notice">{{ session('error') }}</div>@endif
<div class="plans">@foreach($plans as $plan)<article class="plan {{ $plan->is_popular ? 'popular' : '' }}"><h2>{{ $plan->name }}</h2><p>{{ $plan->description }}</p>@if($plan->is_trial)<div class="price">Free <span>/ one month</span></div><ul><li>100 WhatsApp renewal reminders</li><li>Full renewal tracking and reports</li></ul>@if(isset($hasActivePlan) && $hasActivePlan)<div style="margin-top:15px;padding:10px;background:#f8fafc;color:#475569;border-radius:8px;text-align:center;font-size:14px;font-weight:600;">You already have an active plan</div>@else<a class="buy" style="display:block;text-align:center;text-decoration:none" href="{{ auth()->check() ? route('dashboard') : route('register') }}">{{ auth()->check() ? 'Current / free plan' : 'Start free' }}</a>@endif@else<div class="price">₹{{ number_format($plan->monthly_price, 0) }} <span>/ month</span></div><ul><li>{{ number_format($plan->customer_limit) }} customer records</li><li>{{ (int) $plan->whatsapp_limit === 0 ? '∞ Unlimited' : number_format($plan->whatsapp_limit) }} WhatsApp reminders</li><li>Business reports and renewal tracking</li></ul>@auth @if(isset($hasActivePlan) && $hasActivePlan)<div style="margin-top:15px;padding:10px;background:#f8fafc;color:#475569;border-radius:8px;text-align:center;font-size:14px;font-weight:600;">You already have an active plan</div>@else<a class="buy" style="display:block;text-align:center;text-decoration:none" href="{{ route('checkout', ['plan' => $plan->id, 'billing_cycle' => 'monthly']) }}">Buy monthly</a><a class="buy" style="margin-top:9px;background:#0f172a;display:block;text-align:center;text-decoration:none" href="{{ route('checkout', ['plan' => $plan->id, 'billing_cycle' => 'yearly']) }}">Buy yearly · ₹{{ number_format($plan->yearly_price, 0) }}</a>@endif @else<a class="buy" style="display:block;text-align:center;text-decoration:none" href="{{ route('login') }}">Log in to purchase</a>@endauth@endif</article>@endforeach</div></main>
@endsection
@push('scripts')
<!-- Checkout logic moved to checkout page -->
@endpush
